version: '3'

services:

  testdb:
    environment:
      POSTGRES_DB: linker_db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:12.2-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - "5436:5432"
